name: Test action

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install setuptools
        run: apt-get install -y python-setuptools
      - name: PIP install requirements.txt
        run: pip3 install -r requirements.txt
      - name: Test
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          INPUT_DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: python ./test.py
      